local terminal = "kitty"
local browser = "firefox"
local fileManager = "dolphin"
local codeEditor = "code"

hl.bind("SUPER + T", hl.dsp.exec_cmd("" .. terminal .. ""))
hl.bind("SUPER + Return", hl.dsp.exec_cmd("" .. terminal .. ""))
hl.bind("SUPER + SPACE", hl.dsp.exec_cmd([[~/.config/rofi/launchers/launcher.sh]]))
hl.bind("SUPER + W", hl.dsp.exec_cmd("" .. browser .. ""))
hl.bind("SUPER + E", hl.dsp.exec_cmd("" .. fileManager .. ""))
hl.bind("SUPER + C", hl.dsp.exec_cmd("" .. codeEditor .. ""))
hl.bind("SUPER + N", hl.dsp.exec_cmd([[swaync-client -t -sw]]))
hl.bind("SUPER + Slash", hl.dsp.exec_cmd([[~/.config/hypr/scripts/keybinds_hint.sh]]))
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("ALT + F4", hl.dsp.window.close())
hl.bind("SUPER+SHIFT+ALT + Q", hl.dsp.exec_cmd([[hyprctl kill]]))
hl.bind("SUPER+ALT + Space", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + G", hl.dsp.exec_cmd("hyprctl dispatch fullscreen 1"))
hl.bind("SUPER + F", hl.dsp.exec_cmd("hyprctl dispatch fullscreen 0"))
hl.bind("SUPER+ALT + F", hl.dsp.exec_cmd("hyprctl dispatch fullscreenstate 0 3"))
hl.bind("SUPER + O", hl.dsp.exec_cmd("hyprctl dispatch pin "))
hl.bind("SUPER + J", hl.dsp.exec_cmd("hyprctl dispatch layoutmsg togglesplit"))
hl.bind("SUPER + Left", hl.dsp.focus({ direction = "l" }))
hl.bind("SUPER + Right", hl.dsp.focus({ direction = "r" }))
hl.bind("SUPER + Up", hl.dsp.focus({ direction = "u" }))
hl.bind("SUPER + Down", hl.dsp.focus({ direction = "d" }))
hl.bind("SUPER + BracketLeft", hl.dsp.focus({ direction = "l" }))
hl.bind("SUPER + BracketRight", hl.dsp.focus({ direction = "r" }))
hl.bind("SUPER+SHIFT + Left", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER+SHIFT + Right", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER+SHIFT + Up", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER+SHIFT + Down", hl.dsp.window.move({ direction = "d" }))
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind("SUPER + mouse:274", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = "1" }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = "2" }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = "3" }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = "4" }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = "5" }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = "6" }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = "7" }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = "8" }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = "9" }))
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = "10" }))
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = "1" }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = "2" }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = "3" }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = "4" }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = "5" }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = "6" }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = "7" }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = "8" }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = "9" }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = "10" }))
hl.bind("CTRL+SUPER + Right", hl.dsp.focus({ workspace = "r+1" }))
hl.bind("CTRL+SUPER + Left", hl.dsp.focus({ workspace = "r-1" }))
hl.bind("SUPER + Page_Down", hl.dsp.focus({ workspace = "+1" }))
hl.bind("SUPER + Page_Up", hl.dsp.focus({ workspace = "-1" }))
hl.bind("CTRL+SUPER + Page_Down", hl.dsp.focus({ workspace = "r+1" }))
hl.bind("CTRL+SUPER + Page_Up", hl.dsp.focus({ workspace = "r-1" }))
hl.bind("SUPER+SHIFT + mouse_down", hl.dsp.window.move({ workspace = "r-1" }))
hl.bind("SUPER+SHIFT + mouse_up", hl.dsp.window.move({ workspace = "r+1" }))
hl.bind("SUPER+ALT + mouse_down", hl.dsp.window.move({ workspace = "-1" }))
hl.bind("SUPER+ALT + mouse_up", hl.dsp.window.move({ workspace = "+1" }))
hl.bind("SUPER+ALT + Page_Down", hl.dsp.window.move({ workspace = "+1" }))
hl.bind("SUPER+ALT + Page_Up", hl.dsp.window.move({ workspace = "-1" }))
hl.bind("SUPER+SHIFT + Page_Down", hl.dsp.window.move({ workspace = "r+1" }))
hl.bind("SUPER+SHIFT + Page_Up", hl.dsp.window.move({ workspace = "r-1" }))
hl.bind("CTRL+SUPER+SHIFT + Right", hl.dsp.window.move({ workspace = "r+1" }))
hl.bind("CTRL+SUPER+SHIFT + Left", hl.dsp.window.move({ workspace = "r-1" }))
hl.bind("SUPER + mouse_down", hl.dsp.exec_cmd("hyprctl dispatch workspace e+1"))
hl.bind("SUPER + mouse_up", hl.dsp.exec_cmd("hyprctl dispatch workspace e-1"))
hl.bind("ALT + Tab", hl.dsp.workspace.toggle_special("special"))
hl.bind("CTRL + ALT + Tab", hl.dsp.exec_cmd("hyprctl dispatch movetoworkspacesilent special"))
hl.bind("SUPER + mouse:275", hl.dsp.workspace.toggle_special(""))
hl.bind("SUPER + L", hl.dsp.exec_cmd("hyprctl dispatch Lock exec,loginctl lock-session"))
hl.bind("SUPER+SHIFT + L", hl.dsp.exec_cmd("hyprctl dispatch Suspend exec,systemctl suspend || loginctl suspend"), { locked = true })
hl.bind("CTRL+SHIFT+ALT+SUPER + Delete", hl.dsp.exec_cmd("hyprctl dispatch Shutdown exec,systemctl poweroff || loginctl poweroff"))
hl.bind("SUPER + M", hl.dsp.exec_cmd([[command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit]]))
hl.bind("SUPER + P", hl.dsp.exec_cmd([[~/.config/hypr/scripts/monitor_menu.sh]]))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd([[wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+]]), { repeating = true, locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd([[wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-]]), { repeating = true, locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd([[wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle]]), { repeating = true, locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd([[wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle]]), { repeating = true, locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd([[brightnessctl -e4 -n2 set 5%+]]), { repeating = true, locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd([[brightnessctl -e4 -n2 set 5%-]]), { repeating = true, locked = true })
hl.bind("SUPER+SHIFT + P", hl.dsp.exec_cmd([[playerctl play-pause]]), { locked = true })
hl.bind("SUPER+SHIFT + N", hl.dsp.exec_cmd([[playerctl next || playerctl position `bc <<< "100 * $(playerctl metadata mpris:length) / 1000000 / 100"`]]), { locked = true })
hl.bind("SUPER+SHIFT + B", hl.dsp.exec_cmd([[playerctl previous]]), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd([[playerctl play-pause]]), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd([[playerctl play-pause]]), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd([[playerctl next || playerctl position `bc <<< "100 * $(playerctl metadata mpris:length) / 1000000 / 100"`]]), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd([[playerctl previous]]), { locked = true })
hl.bind("SUPER + PRINT", hl.dsp.exec_cmd([[hyprshot -m window]]))
hl.bind("PRINT", hl.dsp.exec_cmd([[hyprshot -m output]]))
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd([[hyprshot -m region]]))
hl.bind("SUPER + SHIFT + C", hl.dsp.exec_cmd([[hyprpicker -a]]))
hl.bind("SUPER + V", hl.dsp.exec_cmd([[cliphist list | rofi -dmenu -p "Clipboard" | cliphist decode | wl-copy]]))
hl.bind("CTRL + SHIFT + grave", hl.dsp.exec_cmd([[pamixer --default-source -t]]))

for i = 1, 9 do
    hl.bind("SUPER + " .. i, hl.dsp.focus({ workspace = tostring(i) }))
    hl.bind("SUPER + SHIFT + " .. i, hl.dsp.window.move({ workspace = tostring(i) }))
end
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = "10" }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = "10" }))
