-- Generated by nwg-displays on 2026-05-22 at 16:06:41. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@100.0",
    position = "3840x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@180.0",
    position = "1920x0",
    scale = 1.0
})
